### ISSUE TITLE
Confusing error message when dynamic schema has errors

### ISSUE THREAD

**Issue by alisdair** [hashicorp/terraform-provider-tfcoremock#34]
Config:

```hcl
resource "tfcoremock_dynamic_resource" "example" {
  nested_map = {
    "foo" = {
      boop = true
      beep = "foop"
    }
    "bar" = {
      beep = "barp"
    }
  }
}
```

`dynamic_resources.json`:

```json
{
  "tfcoremock_dynamic_resource": {
    "attributes": {
      "nested_map": {
        "type": "map",
        "required": true,
        "map": {
          "type": "object",
          "object": {
            "attributes": {
              "boop": {
                "type": "bool"
              },
              "beep": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

This is an invalid schema for several reasons, but the error message doesn't do a great job of helping me figure out why:

```
╷
│ Error: failed to read schema for tfcoremock_dynamic_resource.example in registry.terraform.io/hashicorp/tfcoremock: failed to retrieve schema from provider "registry.terraform.io/hashicorp/tfcoremock": Error converting data source schema: The schema for the data source "tfcoremock_dynamic_resource" couldn't be converted into a usable type. This is always a problem with the provider. Please report the following to the provider developer:
│
│ AttributeName("nested_map"): must have Attributes or Type set
│
```

Notes:

- `Error converting data source schema: The schema for the data source "tfcoremock_dynamic_resource"` is confusing because I'm not using a data source
- `AttributeName("nested_map"): must have Attributes or Type set`: the `nested_map` does have `type` set; the issue is that further down the object type is incorrectly specified

**Comment by alisdair** [comment]
Another example error which could perhaps be better:

```
╷
│ Error: Invalid resource type
│
│   on main.tf line 17, in resource "tfcoremock_dynamic_resource" "agw":
│   17: resource "tfcoremock_dynamic_resource" "agw" {
│
│ The provider hashicorp/tfcoremock does not support resource type "tfcoremock_dynamic_resource".
```

The actual problem was my schema was invalid JSON.

**Comment by liamcervante** [comment]
The original error (when the attribute type is wrong or missing) has actually been fixed by updating to the latest plugin framework which happened in #32 

I've put together a PR that will cause the provider to complain loudly if the JSON file is invalid or doesn't match the schema.
