### ISSUE TITLE
failed to write resource on Windows

### ISSUE THREAD

**Issue by jwoods-ucsb** [hashicorp/terraform-provider-tfcoremock#50]
Using Mock provider for some basic testing. Unable to write out resource 
With the provider configuration:
```
provider "tfcoremock" {
  # Configuration options
  resource_directory = "${path.module}/"
  use_only_state     = false
}
```
I have also tried setting the directory to "./" and "./dirname/"
writing out the example simple resource:

```
resource "tfcoremock_simple_resource" "simple_example" {
  id      = "my-simple-resource"
  bool    = true
  number  = 0
  string  = var.sample_string
  float   = 0
  integer = var.sample_int
}
```
Error is:
```
tfcoremock_simple_resource.simple_example: Creating...
 Error: failed to write resource

   with tfcoremock_simple_resource.simple_example,
   on main.tf line 24, in resource "tfcoremock_simple_resource" "simple_example":
   24: resource "tfcoremock_simple_resource" "simple_example" {

 mkdir ".: The filename, directory name, or volume label syntax is incorrect.
```

This works on Linux and even WSL, but from a CMD or PowerShell terminal it fails.

In comparison, using the Local Provider successfully writes out a file in Windows as expected using 
```
resource "local_file" "foo" {
  content  = "foo!"
  filename = "${path.module}/foo.bar"
}
```

**Comment by liamcervante** [comment]
I've tested your specific example out on a windows machine and it seems to be working with v0.2.0 now.

Thanks so much for filing this issue, and please continue to provide any feedback or highlight any other problems you find!
