### ISSUE TITLE
Missing / wrong example for datasource list into examples

### ISSUE THREAD

**Issue by nnsense** [hashicorp/terraform-provider-tfcoremock#84]
Hi, while using the provider I needed to set a list from a complex resource.
I've found this example into `/examples` 

```
{
  "values": {
  [..]
    "list": {
      "list": [
        {
          "object": {
            "string": {
              "string": "list.one"
            }
          }
        },
        {
          "object": {
            "string": {
              "string": "list.two"
            }
          }
        }
      ]
    }
  }
}
```
But that's apparently a list of objects, am I wrong? It didn't work for me to declare a list of strings, eventually I've set it like this

```
{
  "values": {
    "list": {
      "list": [
        {
          "string": "list.one"
        },
        {
          "string": "list.two"
        }
      ]
    }
  }
}
```

**Comment by liamcervante** [comment]
Hi @nnsense, thanks for the feedback and your interest in the provider! I'm excited to see people other than just me using it!

Are you defining a custom dynamic resource for your list of strings or using the `complex_resource`? Your interpretation here is correct, in that the `list` attribute in the embedded `tfcoremock_complex_resource` does contain nested objects instead of strings. So the data representation in the example represents a configuration like this:

```hcl
resource "tfcoremock_complex_resource" "resource" {
  list = [
    {
      string = "list.one"
    },
    {
      string = "list.two"
    },
  ]
}
```

So, if you're using the `tfcoremock_complex_resource` here then the provided example is correct.

However, if you've defined a custom resource / data source and configured that to contain a list of strings then what you've described looks valid for that use case to me. I'll be happy to review and merge any additional examples you think are missing - if you wanted to raise a PR demonstrating your use case in an example I can take a look and verify everything before I merge it.

I'll leave this open for now in case I've missed something or you have any follow ups!

**Comment by liamcervante** [comment]
Okay, I think I understand what you're trying to do.

The inbuilt resources, `tfcoremock_simple_resource` and `tfcoremock_complex_resource` are not dynamic themselves, so they have a set schema. That means that your data file, `availability-zones.json`, isn't valid when it tries to load into a `tfcoremock_complex_resource`. The inbuilt complex resource only supports collections of nested objects of itself which means you can't provide it a list of strings in that context.

What you can do is define a new dynamic resource, and within the scope of that, provide lists of strings.

Your directory structure will look something like:

- `main.tf`
- `dynamic_resources.json`
- `terraform.data/availability_zones.json`

Your `main.tf` file and `terraform.data` folder can remain largely unchanged, but you'll need to change the type of the resource as we have to give it a different name than `tfcoremock_complex_resource`.

Your `dynamic_resources.json` will be:

```json
{
  "tfcoremock_availability_zones": {
    "attributes": {
      "state": {
        "type": "string",
        "required": true
      },
      "names": {
        "type": "list",
        "required": true,
        "list": {
          "type": "string"
        }
      },
      "zone_ids": {
        "type": "list",
        "required": true,
        "list": {
          "type": "string"
        }
      }
    }
  }
}
```

In there we've defined a new resource type `tfcoremock_availability_zones` with three attributes: `state`, `names`, and `zone_ids`. If you were using this as a resource then all three of those attributes are required, but the required flag is ignored for data sources. The provider also automatically includes an `id` field in any dynamic resources, so your references should all still work.

For full disclosure, I've tested this out with the following `main.tf` configuration file:

```hcl
data "tfcoremock_availability_zones" "availability_zones" {
  id = "data-source"
}

output "zone_ids" {
    value = data.tfcoremock_availability_zones.availability_zones.zone_ids
}
```

And the following data file at `terraform.data/data-source.json`:

```json
{
  "values": {
    "state": {
      "string": "available"
    },
    "names": {
      "list": [
        {
          "string": "us-east-1a"
        },
        {
          "string": "us-east-1b"
        },
        {
          "string": "us-east-1c"
        }
      ]
    },
    "zone_ids": {
      "list": [
        {
          "string": "use1-az1"
        },
        {
          "string": "use1-az2"
        },
        {
          "string": "use1-az3"
        }
      ]
    }
  }
}
```

Hopefully that makes sense, and I've understood your end goal here. Please correct any wrong assumptions I've made, or anything that's not clear!

**Comment by nnsense** [comment]
OK, I think I've got it now, my confusion probably comes from the missing example of a custom resource, so I relied on the existing embedded resources examples, which led me to assume that the `list` was an example for a list instead of a real attribute you can actually use, like `tfcoremock_complex_resource.availability_zones.list`. I would still advise to have a list as a list of strings and a list_object or something along that lines as a list of objects, but I'm sure you had your reasons for that choice.
Also, what I think I'm also getting from your explanation, is that a custom data source _requires_ a matching resource defined to work, pretty much as a "schema", regardless if that resource will actually be ever used, am I getting it correctly?
If it's ok, I will create a PR with my use case, basically the custom resource creation, trying to give a bit more info about this and also the `computed` attribute, which is also missing (at least, I didn't find it) into the docs. Thanks again for your explanation :)

**Comment by liamcervante** [comment]
> Also, what I think I'm also getting from your explanation, is that a custom data source requires a matching resource defined to work, pretty much as a "schema", regardless if that resource will actually be ever used, am I getting it correctly?

Yeah, we don't actually differentiate between data sources and resources when defining dynamic resources so you basically define a "data object" and the provider will make a resource and a data source for it.

> If it's ok, I will create a PR with my use case, basically an example for the custom resource creation

Sounds good 🙂 We do have some examples for this in [here](https://github.com/hashicorp/terraform-provider-tfcoremock/tree/main/examples/dynamic-resources). But, nothing for simple lists yet so happy to see that expanded.

> I'm sure you had your reasons for that choice

It's effectively laziness, in that there is a very large number of possible combinations of collections and data types available and I didn't try and iterate over all of them. With the nested objects, you can do most interesting things as they contain all the interesting data types within them (including more nested collections). So in terms of functionality coverage, you get a lot more with the nested objects than with a simple list of strings.

Thanks for all the feedback, I appreciate it. This is still new, and hasn't had a lot of external engagement so a lot of the missing documentation and examples are a result of that. Thanks again!

**Comment by nnsense** [comment]
Like I said, this is a great provider, there's a terraform certification and a lot of people are learning it, there is a lot to learn in terms of scripting with terraform, with this I can create all my fake AWS resources and datasources and pretend to deploy focusing on logic/scripting instead of configuration and deployment, and deployment waaaaaaaaaay quicker than the real thing! That's why I searched for a "mock" provider and here it is :) I will try to help the best I can, thanks Liam :)
